#ABNF 1.0 ISO8859-1;

// GARBAGE Built-in
// Copyright: Verbio Technologies S.L.

root $garbage = 
ace |
ant |
//back |
bag |
band |
bash |
bed |
best |
//blank |
blind |
boat |
boat |
born |
brain |
bread |
call |
cap |
cart |
cat |
choke |
clock |
close |
club |
coat |
crew |
crop |
cry |
cut |
cute |
dive |
dorm |
draw |
drew |
dump |
dust |
dwell |
east |
feed |
first |
fish |
flag |
flap |
flesh |
flow |
for |
four |
//gate |
gear |
gel |
glaze |
green |
grow |
hack |
//hall |
ham |
//hand |
hang |
hat |
hat |
hate |
head |
heal |
heart |
heat |
here |
high |
hunt |
ice |
inch |
//ink |
jug |
keep |
key |
kind |
lamp |
land |
learn |
less |
//lie |
//light |
lip |
long |
look |
look |
lump |
//mail |
//man |
match |
milk |
//mind |
mint |
//mode |
mush |
net |
noise |
//old |
orange |
park |
pear |
peg |
plant |
play |
point |
poor |
price |
print |
proud |
proud |
pull |
quick |
rag |
//rail |
reach |
red |
rest |
ring |
ripe |
//robe |
rock |
roll |
room |
root |
rope |
rule |
run |
seam |
seat |
seize |
shark |
sharp |
sheet |
shoe |
shop |
show |
shy |
sick |
side |
size |
skirt |
slope |
smoke |
smooth |
//sold |
//tax |
tell |
time |
toe |
toll |
top |
trade |
trick |
vase |
vent |
verse |
void |
wait |
waste |
why |
will |
wood |
work |
worm |
worn;


