#ABNF 1.0 ISO8859-1;

public $chain = ($D $SIL*)+;
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Gramáticas Auxiliares
// ---------------------------------------------------------------------------
$SIL =  "[SIL]" {};

$D = (
	[double] {D01} one {D01} |
     [double] {D02} two {D02} |
     [double] {D03} three {D03} |
     [double] {D04} four {D04} |
     [double] {D05} five {D05} |
     [double] {D06} six {D06} |
     [double] {D07} seven {D07} |
     [double] {D08} eight {D08} |
     [double] {D09} nine {D09} |
     [double] {D00} zero {D00} |
     [double] {D00} oh {D00}
	);
// ---------------------------------------------------------------------------
