#ABNF 1.0 ISO8859-1;

// GARBAGE Built-in
// Copyright: Verbio Technologies S.L.

root $garbage =
sobre |
todos |
você |
ainda |
assim |
porque |
disse |
tudo |
tempo |
vida |
então |
homem |
pois |
pode |
deus |
onde |
senhor |
grande |
sempre |
fazer |
havia |
outro |
todo |
nada |
outros |
coisa |
parte |
agora |
toda |
mundo |
casa |
dois |
apenas |
todas |
cada |
anos |
contra |
qualquer |
antes |
quanto |
menos |
olhos |
aqui |
homens |
estado |
direito |
dizer |
pouco |
outra |
forma |
nunca |
terra |
coisas |
verdade |
poder |
vezes |
meio |
enquanto |
lado |
tanto |
como |
trabalho |
porém |
três |
melhor |
duas |
pessoas |
alguma |
primeiro |
deve |
alguns |
lugar |
filho |
modo |
nome |
noite |
segundo |
novo |
mesma |
maior |
sido |
quase |
mulher |
outras |
cabeça |
hoje |
quer |
povo |
caso |
fato |
brasil |
dias |
história |
quando |
logo |
durante |
cidade |
talvez |
desde |
embora |
estão |
primeira |
além |
momento |
próprio |
sendo |
algum |
podia |
natureza |
dentro |
ninguém |
gente |
mãos |
corpo |
palavras |
razão |
para |
força |
ordem |
quais |
sociedade |
saber |
própria |
política |
amor |
espírito |
poderia |
ponto |
certo |
país |
nova |
filhos |
morte |
governo |
muitos |
maneira |
falar |
guerra |
disso |
sabe |
idéia |
possível |
causa |
estar |
vontade |
social |
diante |
paulo |
palavra |
pessoa |
grandes |
nenhum |
rosto |
coração |
livro |
podem |
porta |
muitas |
algumas |
geral |
desta |
desse |
sentido |
exemplo |
relação |
volta |
parece |
hora |
frente |
alguém |
caminho |
dessa |
deste |
tarde |
ficou |
nacional |
senão |
respeito |
preciso |
água |
neste |
feito |
número |
portanto |
depois |
velho |
ficar |
leis |
dinheiro |
algo |
queria |
somente |
vista |
quero |
vossa |
família |
demais |
quatro |
respondeu |
liberdade |
vamos |
claro |
sabia |
processo |
nesse |
após |
sistema |
parecia |
pensamento |
tais |
isso |
realmente |
nenhuma |
alma |
jesus |
simples |
época |
valor |
obra |
horas |
através |
ação |
tendo |
joão |
mulheres |
olhar |
final |
conhecimento |
haviam |
conta |
seguinte |
posso |
sangue |
jamais |
amigo |
quem |
problema |
longe |
cinco |
quarto |
tipo |
perguntou |
idéias |
realidade |
cima |
alto |
apesar |
pensar |
justiça |
movimento |
princípio |
espécie |
estados |
junto |
deixar |
século |
acho |
contrário |
forças |
necessidade ;
