#ABNF 1.0 ISO8859-1;

root $phone = [zero {U0} $longDistanceCode] $areaCode [$mandatoryCellPhone] $eightNumbers;


$longDistanceCode =
    doze {D1 U2} |
    catorze {D1 U4} |
    quinze {D1 U5} |
    "vinte e um" {D2 U1} |
    "trinta e um" {D3 U1} |
    "quarenta e um" {D4 U1} |
    "quarenta e três" {D4 U3}
;

$areaCode = $ten | $unit $unit;

$mandatoryCellPhone =
    nove {U9}  |
    novecentos {C9}
;


$eightNumbers = (
    $hundred $unit $unit $ten $unit |
    $ten $unit $ten $unit $ten |
    $ten $ten $hundred $unit |
    $unit $unit $hundred $ten $unit |
    $unit $ten $unit $ten $unit $unit |
    $hundred $hundred $ten |
    $ten $unit $unit $unit $hundred |
    $unit $ten $unit $hundred $unit |
    $unit $unit $hundred $hundred |
    $ten $unit $hundred $unit $unit |
    $ten $ten $unit $ten $unit |
    $unit $hundred $hundred $unit |
    $hundred $unit $ten $unit $unit |
    $ten $unit $hundred $ten |
    $ten $ten $unit $hundred |
    $ten $unit $ten $hundred |
    $hundred $ten $ten $unit |
    $hundred $unit $ten $ten |
    $unit $hundred $unit $hundred |
    $hundred $ten $hundred |
    $unit $ten $hundred $unit $unit |
    $ten $ten $ten $ten |
    $hundred $unit $hundred $unit |
    $unit $ten $hundred $ten |
    $ten $hundred $unit $ten |
    $unit $ten $ten $ten $unit |
    $hundred $hundred $unit $unit |
    $unit $unit $unit $ten $hundred |
    $ten $unit $unit $hundred $unit |
    $ten $unit $unit $ten $unit $unit |
    $ten $unit $ten $ten $unit |
    $unit $unit $hundred $unit $unit $unit |
    $hundred $unit $unit $hundred |
    $unit $unit $unit $ten $unit $unit $unit |
    $hundred $ten $unit $ten |
    $unit $ten $ten $hundred |
    $unit $unit $ten $hundred $unit |
    $unit $hundred $unit $ten $unit |
    $ten $hundred $unit $unit $unit |
    $ten $hundred $hundred |
    $unit $unit $ten $ten $unit $unit |
    $unit $unit $ten $unit $ten $unit |
    $ten $hundred $ten $unit |
    $unit $ten $unit $unit $unit $unit $unit |
    $unit $unit $hundred $unit $ten |
    $unit $unit $unit $unit $unit $unit $ten |
    $hundred $ten $unit $unit $unit |
    $unit $ten $ten $unit $ten |
    $ten $ten $ten $unit $unit |
    $unit $unit $ten $unit $hundred |
    $ten $unit $unit $unit $ten $unit |
    $ten $ten $unit $unit $unit $unit |
    $ten $ten $unit $unit $ten |
    $unit $unit $unit $hundred $unit $unit |
    $unit $hundred $unit $unit $unit $unit |
    $unit $unit $unit $unit $unit $ten $unit |
    $unit $hundred $ten $unit $unit |
    $unit $unit $unit $unit $ten $unit $unit |
    $ten $unit $unit $ten $ten |
    $hundred $unit $unit $unit $unit $unit |
    $unit $ten $unit $unit $hundred |
    $unit $hundred $unit $unit $ten |
    $unit $hundred $ten $ten |
    $hundred $unit $unit $unit $ten |
    $unit $ten $ten $unit $unit $unit |
    $unit $unit $ten $ten $ten |
    $unit $unit $unit $ten $ten $unit |
    $unit $ten $unit $unit $ten $unit |
    $unit $ten $unit $unit $unit $ten |
    $ten $unit $ten $unit $unit $unit|
    $unit $unit $ten $unit $unit $unit $unit |
    $ten $unit $unit $unit $unit $ten |
    $unit $unit $unit $unit $unit $unit $unit $unit |
    $unit $unit $unit $unit $ten $ten |
    $ten $unit $unit $unit $unit $unit $unit |
    $unit $unit $unit $unit $hundred $unit |
    $unit $unit $unit $hundred $ten |
    $unit $unit $unit $ten $unit $ten |
    $unit $unit $ten $unit $unit $ten |
    $unit $unit $unit $unit $unit $hundred |
    $thousand $thousand |
    $thousand $unit $unit $unit $unit |
    $unit $unit $unit $unit $thousand |
    $unit $unit $thousand $unit $unit |
    $unit $thousand $unit $unit $unit |
    $unit $unit $unit $thousand $unit |
    $thousand $ten $ten |
    $ten $ten $thousand |
    $ten $thousand $ten |
    $thousand $ten $unit $unit |
    $unit $unit $ten $thousand |
    $unit $ten $unit $thousand |
    $thousand $unit $ten $unit |
    $ten $thousand $unit $unit |
    $thousand $unit $unit $ten |
    $unit $unit $thousand $ten |
    $ten $unit $unit $thousand |
    $ten $unit $thousand $unit |
    $unit $ten $thousand $unit |
    $unit $thousand $ten $unit
);


$thousand = ($thousandAlone | $thousandAssembled);
$hundred = ($hundredAlone | $hundredAssembled);
$ten = $tenAlone | $tenAssembled;

$SIL =  "[SIL]" {};


$thousandAssembled = (
    ($thousandPosition ($hundredAlone | $tenAlone | $unitWithoutZero)) |
    ($thousandPosition $hundredAssembled) |
    ($thousandPosition $tenAssembled)
);

$thousandAlone = (
    "mil" {K1000} |
    "dois mil" {K2000} |
    "três mil" {K3000} |
    "quatro mil" {K4000} |
    "cinco mil" {K5000} | 
    "seis mil" {K6000} |
    "sete mil" {K7000} | 
    "oito mil" {K8000} |
    "nove mil" {K9000}
);

$thousandPosition = (
    "mil e" {K1} |
    "dois mil e" {K2} |
    "três mil e" {K3} |
    "quatro mil e" {K4} |
    "cinco mil e" {K5} |
    "seis mil e" {K6} |
    "sete mil e" {K7} |
    "oito mil e" {K8} |
    "nove mil e" {K9}
);


$hundredAssembled = ($hundredPosition $tenAlone | $hundredPosition $tenAssembled | $hundredPosition $unitWithoutZero);

$hundredAlone = (
    cem {C100} |
    duzentos {C200} |
    trezentos {C300} |
    quatrocentos {C400} |
    quinhentos {C500} |
    seiscentos {C600} |
    setecentos {C700} |
    oitocentos {C800} |
    novecentos {C900}
);

$hundredPosition = (
    "cento e" {C1} |
    "duzentos e" {C2} |
    "trezentos e" {C3} |
    "quatrocentos e" {C4} |
    "quinhentos e" {C5} |
    "seiscentos e" {C6} |
    "setecentos e" {C7} |
    "oitocentos e" {C8} |
    "novecentos e" {C9} 
);


$tenAssembled = $tenPosition $unitWithoutZero;

$tenAlone = 
    dez 	{D10} 		|
    onze 	{D1 U1}		|
    doze 	{D1 U2} 	|
    treze 	{D1 U3} 	|
    catorze 	{D1 U4} 	|
    quinze 	{D1 U5} 	|
    dezesseis 	{D1 U6} 	|
    dezessete 	{D1 U7} 	|
    dezoito 	{D1 U8} 	|
    dezenove 	{D1 U9} 	|
    vinte 	{D20} $SIL 	|
    trinta 	{D30} $SIL 	|
    quarenta 	{D40} $SIL 	|
    cinquenta 	{D50} $SIL 	|
    sessenta 	{D60} $SIL 	|
    setenta 	{D70} $SIL 	|
    oitenta 	{D80} $SIL 	|
    noventa 	{D90} $SIL	;

$tenPosition = (
    "vinte e" {D2} |
    "trinta e" {D3} |
    "quarenta e" {D4} |
    "cinquenta e" {D5} |
    "sessenta e" {D6} |
    "setenta e" {D7} |
    "oitenta e" {D8} |
    "noventa e" {D9}
);


$unitWithoutZero = (
    um {U1} |
    dois {U2} |
    três {U3} |
    quatro {U4} |
    cinco {U5} |
    seis {U6} |
    meia {U6} |
    sete {U7} |
    oito {U8} |
    nove {U9}
);

$unit = (
    zero {U0} |
    um {U1} |
    dois {U2} |
    três {U3} |
    quatro {U4} |
    cinco {U5} |
    seis {U6} |
    meia {U6} |
    sete {U7} |
    oito {U8} |
    nove {U9}
);

