#ABNF 1.0 ISO8859-1

language pt-br;
mode voice;


root $number = $GARBAGE*  $numberComplete  $GARBAGE* ;

$SIL = "[SIL]" {};

$numberComplete = ($complet | $decimal) ;

$complet = $integer reais {cBRL} [(com | e) {} $decimalPart [centavos {}]] ;
$decimal = ($decimalPart [centavos] {cBRL}) ;

    
$integer = ($billion | $hundredMillion | $tenMillion | $million | $hundredThousand | $tenThousand | $thousand | 
$hundred | $ten | $unit) ;


$billion = (
    $unit (bilho|bilhes) {BILLION} |
    $unit (bilho|bilhes) {BILLION} [e] {}
    (
        $hundredMillion |
        $tenMillion |
        $ten |
        $hundred |
        $thousand |
        $tenThousand |
        $million |
        $hundredThousand
    )
);

$hundredMillion = (
    $hundred (milhes) {MILLION} |
    $hundred (milhes) {MILLION} [e] {}
    (
        $hundredThousand |
        $tenMillion |
        $ten |
        $hundred |
        $thousand |
        $tenThousand |
        $million
    )
);

$tenMillion = (
    $ten (milhes) {MILLION} |
    $ten (milhes) {MILLION} [e] {}
    (
        $hundredThousand |
        $ten |
        $hundred |
        $thousand |
        $tenThousand |
        $million |
        $hundredThousand
    )
);

$million = (
    $unit (milho|milhes) {MILLION} |
    (
        $unit (milho|milhes) {MILLION} [e] {}
        (
            $ten |
            $hundred |
            $thousand |
            $tenThousand |
            $hundredThousand
        )
    )
);

$hundredThousand = (
    $hundred (mil) {THOUSAND} |
    $hundred (mil) {THOUSAND} [e] {} ($hundred | $ten | $unit)
);

$tenThousand = (
    $ten (mil) {THOUSAND} |
    $ten (mil) {THOUSAND} [e] {} ($ten | $unit | $hundred)
);

$thousand = (
    $unit (mil) {THOUSAND} |
    $unit (mil) {THOUSAND} [e {}] ($ten | $unit | $hundred)
);
$hundred = ($hundredPosition | $hundredAssembled) ;
$ten = ($tensPosition | $tenAssembled | $tensAlone) ;


$unit = (
    (zero)    {U0} |
    (um )     {U1} |
    (dois)    {U2} |
    (três)    {U3} |
    (quatro)  {U4} |
    (cinco)   {U5}  |
    (seis)    {U6}  |
    (meia)    {U6} |
    (sete)    {U7} |
    (oito)    {U8} |
    (nove)    {U9} 
);


$tensPosition = (
    (vinte) {D2} |
    (trinta) {D3} |
    (quarenta) {D4} |
    (cinquenta) {D5} |
    (sessenta) {D6} |
    (setenta) {D7} |
    (oitenta) {D8} |
    (noventa) {D9}  
);

$tensAlone = (
    (dez)  {D1}    |
    (déis)  {D1}    |
    (onze)  {D1 U1}   |
    (doze)  {D1 U2}   |
    (treze)  {D1 U3}  |
    (catorze)  {D1 U4}  |
    (quinze)  {D1 U5}   |
    (dezesseis)  {D1 U6}   |
    (dezessete)  {D1 U7}   |
    (dezoito)  {D1 U8}   |
    (dezenove)  {D1 U9}   
);

$tenAssembled = ($tensPosition (e) {} $unit) ;


$hundredPosition = (
    (cento)             {C1} |
    (cem)               {C1} |
    (duzentos)         {C2} | (duzentas)                 {C2} |
    (trezentos)       {C3} | (trezentas)                {C3} |
    (quatrocentos)     {C4} | (quatrocentas)              {C4} |
    (quinhentos)       {C5} | (quinhentas)                {C5} |
    (seiscentos)     {C6} | (seiscentas)               {C6} |
    (setecentos)      {C7} | (setecentas)                {C7} |
    (oitocentos)      {C8} | (oitocentas)                {C8} |
    (novecentos)      {C9} | (novecentas)                {C9}
);

$hundredAssembled = ($hundredPosition (e) {}  ($tensPosition |$tenAssembled | $tensAlone | $unit )) ;


$decimalPart = ( $unitsDecimalPart+  |  $decimalTen  |  $decimalHundred );

$decimalTen = ($decimalTenAssembled | $decimalTenAlone | $decimalTenPosition);
$decimalHundred = ($decimalHundredPosition |$decimalHundredAssembled) ;
$decimalHundredAssembled = ($decimalHundredPosition (e) {} ($decimalTen | $unitsDecimalPart));
$decimalTenAssembled = ($decimalTenPosition (e) {} $unitsDecimalPart);


$decimalHundredPosition =  (
    (cento)             {X1} |
    (cem)                  {X1} |
    (duzentos)         {X2} | (duzentas)                 {X2} |
    (trezentos)       {X3} | (trezentas)                {X3} |
    (quatrocentos)     {X4} | (quatrocentas)              {X4} |
    (quinhentos)       {X5} | (quinhentas)                {X5} |
    (seiscentos)     {X6} | (seiscentas)               {X6} |
    (setecentos)      {X7} | (setecentas)                {X7} |
    (oitocentos)      {X8} | (oitocentas)                {X8} |
    (novecentos)      {X9} | (novecentas)                {X9}
);


$decimalTenPosition = (
    (vinte) {Y2} |
    (trinta) {Y3} |
    (quarenta) {Y4} |
    (cinquenta) {Y5} |
    (sessenta) {Y6} |
    (setenta) {Y7} |
    (oitenta) {Y8} |
    (noventa) {Y9}
);

$decimalTenAlone = (
    (dez)  {Y1}   |
    (déis)  {Y1}  |
    (onze)  {Y1 Z1}  |
    (doze)  {Y1 Z2} |
    (treze)  {Y1 Z3}   |
    (catorze)  {Y1 Z4}  |
    (quinze)  {Y1 Z5}   |
    (dezesseis)  {Y1 Z6} |
    (dezessete)  {Y1 Z7}  |
    (dezoito)  {Y1 Z8}  |
    (dezenove)  {Y1 Z9}  
);


$unitsDecimalPart = (
    (zero)    {Z0} |
    (um )     {Z1} |
    (dois)    {Z2} |
    (três)    {Z3} |
    (quatro)  {Z4} |
    (cinco)   {Z5}  |
    (seis)    {Z6}  |
    (meia)    {Z6} |
    (sete)    {Z7} |
    (oito)    {Z8} |
    (nove)    {Z9} 
);
